# Generated by Django 4.2.7 on 2024-02-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("avto", "0002_carmodel_carannouncement_alter_contact_car_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotoMarka",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                ("car", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="avto.carmodel")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
